### ISSUE TITLE
java.util.zip.ZipException

### ISSUE THREAD

**Issue by chenxuuu** [CCEmuX/launcher#2]
can't open `ccemux-launcher.jar`

```powershell
PS C:\Users\chenx\Desktop> java -jar ccemux-launcher.jar
Starting CCEmuX launcher
Emulator version: EmuVersion(hash=88ba9e7a, build=cct)
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at cc.emux.launcher.Launcher.main(Launcher.kt:96)
PS C:\Users\chenx\Desktop> java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by SquidDev** [comment]
Can you try deleting `%APPDATA%\ccemux\versions` and trying again? It's possible the download was corrupted.

**Comment by chenxuuu** [comment]
ok it works
but downloading `https://emux.cc/versions/88ba9e7a/CCEmuX-cct.jar` is too slow...

**Comment by SquidDev** [comment]
Hrmrm, that's odd. It's pretty fast on my machine (~1.4 seconds). The server is in France, so I realise it's a fair distance for you, but it shouldn't make _that_ much difference.

**Comment by chenxuuu** [comment]
maybe...you can upload a `CCEmuX-cct.jar` to GitHub release page?
it's very fast with aria2🤔
